In [11]:
# pandas = panel datas
# 1 dimensional array = Series / 2 dimensional array = DataFrame

# DataFrame : row구분(index), column구분(column)
# 한 번 설정된 index는 변경 불가
import pandas as pd
import numpy as np
index=pd.date_range('1/1/2000', periods=8) # 날짜 형태로된 8개의 index
print(index)

#numpy rand 8행 3열짜리 [0,1)data 생성
df=pd.DataFrame(np.random.rand(8,3), index=index, columns=list('ABC'))
df

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

                   A         B         C
2000-01-01  0.135229  0.414011  0.771692
2000-01-02  0.019738  0.112246  0.125738
2000-01-03  0.857735  0.519912  0.508717
2000-01-04  0.388971  0.427153  0.289321
2000-01-05  0.584779  0.895488  0.791035
2000-01-06  0.186696  0.815153  0.221501
2000-01-07  0.144670  0.920898  0.691112
2000-01-08  0.588184  0.907614  0.097614

In [19]:
import pandas as pd
import numpy as np
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.rand(8,3), index=index, columns=list('ABC'))


#df column access = 대괄호에 column이름 넣기
print('col access')
print(df['A']) # Series형태 index=기본 인덱스, 1차원 배열형태

#mask기능 (return Series of boolean values. 원하는 데이터 골라내기)
print('\nmask')
print(df['B'] > 0.4)

#B열의 값이 0.4보다 큰 값이라는 조건이 True인 데이터(row select)들로만 이루어진 데이터 프레임
#Series of boolean values can be used to filter the DataFrame by putting it in between the selection brackets []. Only rows for which the value is True will be selected.
#source : https://pandas.pydata.org/docs/getting_started/intro_tutorials/03_subset_data.html
df2=df[df['B'] > 0.4]
print('\nmask adapted table')
print(df2)

#행과 열 뒤집기 Transpose
print('\ntranspose table')
print(df.T)

col access
2000-01-01    0.780182
2000-01-02    0.758702
2000-01-03    0.394168
2000-01-04    0.468546
2000-01-05    0.507170
2000-01-06    0.538521
2000-01-07    0.039585
2000-01-08    0.449789
Freq: D, Name: A, dtype: float64

mask
2000-01-01     True
2000-01-02     True
2000-01-03    False
2000-01-04     True
2000-01-05     True
2000-01-06    False
2000-01-07    False
2000-01-08    False
Freq: D, Name: B, dtype: bool

mask adapted table
                   A         B         C
2000-01-01  0.780182  0.408965  0.351861
2000-01-02  0.758702  0.754951  0.323564
2000-01-04  0.468546  0.741702  0.161611
2000-01-05  0.507170  0.608710  0.466334

transpose table
   2000-01-01  2000-01-02  2000-01-03  2000-01-04  2000-01-05  2000-01-06  \
A    0.780182    0.758702    0.394168    0.468546    0.507170    0.538521
B    0.408965    0.754951    0.335851    0.741702    0.608710    0.341707
C    0.351861    0.323564    0.839743    0.161611    0.466334    0.506787

   2000-01-07  2000-01-08
A    0.039585    0.449789
B    0.300042    0.239178
C    0.688302    0.308312

In [28]:
# 2 dimensional array, DataFrame operation
# row 방향 연산 axis = 0
# col 방향 연산 axis = 1
import pandas as pd
import numpy as np
index = pd.date_range('1/1/2000', periods=8)
df = pd.DataFrame(np.random.rand(8,3), index=index, columns=list('ABC'))

# A열의 값을 B열의 값으로 나눈 값을 D열에 저장
df['D']= df['A']/df['B']

# 행 우선(row major ordering,가로로) 계산 값을 E열에 저장 / 'columns'방향
df['E'] = np.sum(df, axis=1)
print(df.head())
# 열 우선(column major ordering, 세로로) 계산 / 'index'방향
# A열 값 기준으로 전체 데이터에 대한 뺄셈
df= df.sub(df['A'], axis=0)

print(df.head()) # 앞 5개

                   A         B         C         D         E
2000-01-01  0.326939  0.252397  0.681479  1.295337  2.556152
2000-01-02  0.075766  0.558540  0.174636  0.135650  0.944592
2000-01-03  0.635741  0.964838  0.824718  0.658910  3.084207
2000-01-04  0.512054  0.372846  0.172306  1.373366  2.430572
2000-01-05  0.163430  0.702359  0.315226  0.232687  1.413702
              A         B         C         D         E
2000-01-01  0.0 -0.074542  0.354540  0.968397  2.229213
2000-01-02  0.0  0.482774  0.098870  0.059884  0.868826
2000-01-03  0.0  0.329097  0.188977  0.023168  2.448466
2000-01-04  0.0 -0.139208 -0.339748  0.861312  1.918518
2000-01-05  0.0  0.538929  0.151795  0.069257  1.250272